# Generated by Django 5.0.3 on 2024-03-09 05:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_skills_profile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
