# Generated by Django 5.0.3 on 2024-03-09 04:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="topic",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
