# Generated by Django 5.0.3 on 2024-03-09 01:29

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="courses")),
                ("description", models.TextField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1st year", "1st year"),
                            ("2nd year", "2nd year"),
                            ("3rd year", "3rd year"),
                            ("4th year", "4th year"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Computer", "Computer"),
                            ("Technology", "Technology"),
                            ("Art", "Art"),
                            ("Music", "Music"),
                            ("Economics", "Economics"),
                        ],
                        max_length=100,
                    ),
                ),
                ("duration", models.CharField(max_length=100)),
                ("skill_level", models.CharField(max_length=100)),
                ("over_view", ckeditor.fields.RichTextField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video", models.FileField(blank=True, upload_to="lectures")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courses",
                    ),
                ),
            ],
        ),
    ]
