# Generated by Django 5.0.3 on 2024-03-09 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_lectures_video_lectures_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectures",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="courses.courses",
            ),
        ),
    ]
